FROM node:20-alpine

# create a working directory

WORKDIR /app

#Install app dependencies

COPY  package*.json ./

# Run npm install
RUN npm install


#Bundle app source
COPY . .

# Expose
EXPOSE 8000

# Run app
CMD ["npm", "start"]

